### ISSUE TITLE
Spam by default

### ISSUE THREAD

**Issue by cemeyer** [fedora-infra/fedora-tagger#187]
I'm a volunteer Fedora developer. I never signed up for email from this thing, and get one every time someone "upvotes" a "tag" (whatever that means) on a package I {watch|maintain|not really sure}. Please don't email people who don't ask you for email.

**Comment by pypingou** [comment]
The emails are not send by this application but by FMN: https://apps.fedoraproject.org/notifications/

I would encourage you to login there and adjust your settings to ignore these notifications.

Note: the current default settings do ignore these notifications, so you could just reset your whole profile (but that depends on how much tweaking you did to it).

**Comment by cemeyer** [comment]
I haven't mucked about with the notifcation settings at all. I never asked for this email. Talk to whoever you have to talk to, but I'm getting tagger emails and I never signed up for them.

**Comment by pypingou** [comment]
Are you a Fedora packager?

**Comment by ralphbean** [comment]
@cemeyer we announced a couple times that we'd be turning on this notifications system for packagers on the devel-announce list:  https://lists.fedoraproject.org/pipermail/devel-announce/2015-February/001533.html

**Comment by cemeyer** [comment]
> Are you a Fedora packager?

Very first sentence in this bug, friend:

> I'm a volunteer Fedora developer.

@ralphbean, Please turn it back off.

**Comment by ralphbean** [comment]
> @ralphbean, Please turn it back off.

What's your FAS username?

**Comment by pypingou** [comment]
There are many meanings to developer, you could be writing code and not packaging :)

**Comment by cemeyer** [comment]
@ralphbean , Sorry, to clarify notifications in general are ok. I just don't want the crap from Tagger. I tried to deselect it in notification settings but am not sure I was successful. FAS username is "konradm".

**Comment by ralphbean** [comment]
@cemeyer by looking at your settings, it seems like you were successful.

If you get any more tagger spam, let us know and we can investigate further.
