### ISSUE TITLE
tagger is super slow

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fedora-tagger#190]
Lately tagger is super slow. 

```
% time wget https://apps.fedoraproject.org/tagger/
...
wget https://apps.fedoraproject.org/tagger/  0.01s user 0.01s system 0% cpu 2:11.98 total
```

dmesg on the tagger hosts has a number of segfaults:
```
[952425.194830] httpd[14527]: segfault at 8 ip 00007ffc25a4dd40 sp 00007ffc1e1f2db0 error 4 in libpython2.7.so.1.0[7ffc25953000+178000]
```

apache error_log has:
```
[Sat Jun 13 20:37:40.828248 2015] [:error] [pid 18167] /usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py:585: SAWarning: Unicode type received non-unicodebind param value.
[Sat Jun 13 20:37:40.828307 2015] [:error] [pid 18167]   processors[key](compiled_params[key])
```

Could be some unicode tags causing issues?

**Comment by major** [comment]
I've noticed the same.  Is there any way to test fedora-tagger from GitHub with real data?

![Pingdom](https://dl.dropboxusercontent.com/1/view/xevy27w0nww1lfq/Apps/Shutter/fedora_tagger_pingdom.png)

**Comment by ralphbean** [comment]
Not sure about directly from GitHub, but we do have a [nightly dump of the production db](http://infrastructure.fedoraproject.org/infra/db-dumps/) to help with local testing.  We just haven't had/made engineering time to address it.

**Comment by ralphbean** [comment]
OK, with that cache change and some ``/etc/hosts`` tweaks, tagger should be usable again.  Please lemme know if it acts up again.
